import { describe, expect, it } from 'vitest';
import { existsSync } from 'fs';
import path from 'path';
import { getDemoEntries, deriveDemoSlug } from '@/lib/content';
import { DEMO_SLUG_TARGETS } from '@/lib/demo-slug-map';

/**
 * src/lib/demo-slug-map.ts is generated by scripts/generate-demo-slug-map.mjs,
 * which carries its own copy of the frontmatter parsing and the public/ walk
 * (content.ts is TypeScript, the generator is plain node). These tests are the
 * guard against the two drifting: if a demo is added, renamed or re-pathed and
 * the generator is not rerun, the clean URL would 404 in production - here it
 * fails instead.
 *
 *   node scripts/generate-demo-slug-map.mjs
 */
describe('demo slug map', () => {
  const entries = getDemoEntries();

  it('has at least one demo to check', () => {
    expect(entries.length).toBeGreaterThan(0);
  });

  it('covers every demo in content/demos exactly once', () => {
    expect(Object.keys(DEMO_SLUG_TARGETS).sort()).toEqual(entries.map((e) => e.slug).sort());
  });

  it('points every slug at the same file content.ts resolves', () => {
    for (const entry of entries) {
      expect(DEMO_SLUG_TARGETS[entry.slug]?.html, entry.slug).toBe(entry.path);
    }
  });

  it('points every dir at the folder holding that file', () => {
    for (const target of Object.values(DEMO_SLUG_TARGETS)) {
      expect(target.dir).toBe(target.html.slice(0, target.html.lastIndexOf('/')));
    }
  });

  it('resolves every target to a file that exists under public/', () => {
    for (const [slug, target] of Object.entries(DEMO_SLUG_TARGETS)) {
      const filePath = path.join(
        process.cwd(),
        'public',
        decodeURIComponent(target.html).replace(/^\//, ''),
      );
      expect(existsSync(filePath), `${slug} -> ${filePath}`).toBe(true);
    }
  });

  it('only produces slugs the proxy will route', () => {
    for (const slug of Object.keys(DEMO_SLUG_TARGETS)) {
      // Kebab-case ASCII, and never "demo" + a digit: the proxy matcher
      // deliberately ignores /demos/demoN/... so such a slug is unroutable.
      expect(slug).toMatch(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
      expect(slug).not.toMatch(/^demo\d/);
    }
  });

  it('derives slugs from the human title, dropping the descriptive tail', () => {
    expect(deriveDemoSlug('Rush Energy - Energy Drink Analytics')).toBe('rush-energy');
    expect(deriveDemoSlug('Falcon Food & Snacks')).toBe('falcon-food-snacks');
    expect(deriveDemoSlug('  Falcon PMR  ')).toBe('falcon-pmr');
    expect(deriveDemoSlug('Falcon Telecom & Media')).toBe('falcon-telecom-media');
  });
});
